### PR TITLE
Increments to v2.4.0

### PR DESCRIPTION
**Pull request by dirmeier**

### CODE REVIEW

**Comment by dirmeier** [comment]
@conda-forge-admin, please rerender

**Review by singerj — COMMENTED** [review]
in meta.yaml:
- test -f $PREFIX/share/cmake/Modules/FindSeqAn.cmake  # [unix] should be - test -f $PREFIX/share/cmake/seqan-config.cmake  # [unix]
- if not exist "%PREFIX%"\\share\\cmake\\Modules\\FindSeqAn.cmake exit 1  # [win] should be - if not exist "%PREFIX%"\\share\\cmake\\Modules\\seqan-config.cmake exit 1  # [win]

**Comment by dirmeier** [comment]
Dear @bgruening, could you please have a look at this and merge if possible?

**Comment by bgruening** [comment]
@dirmeier looks good to me. Do you want to add yourself as maintainer?

ping @aseyboldt as real maintainer here. I will merge tomorrow if @aseyboldt is too busy.

**Comment by dirmeier** [comment]
Hi Björn, wow that was quick. No, sorry, I don't have the time :/. I was just setting up this for a colleague.

@aseyboldt Is it ok with you to merge this?

**Comment by bwlang** [comment]
thanks for the work on this... i'm hoping to use it to update the flexbar wrapper in bioconda 👍

**Comment by aseyboldt** [comment]
@dirmeier This looks good, thank you!
Unfortunately I haven't been much of a good maintainer recently, I don't use seqan anymore myself...

**Comment by dirmeier** [comment]
Hey @aseyboldt, thanks for the merge. No worries, everyone is busy and it's hard to find time for OSS.

**Pull request merged**
